QUERY 1-

1.1 Import the csv file of the stock you have been allotted using 'pd.read_csv()' function into a dataframe.
Shares of a company can be offered in more than one category. The category of a stock is indicated in the ‘Series’ column. If the csv file has data on more than one category, the ‘Date’ column will have repeating values. To avoid repetitions in the date, remove all the rows where 'Series' column is NOT 'EQ'.
Analyze and understand each column properly.
You'd find the head(), tail() and describe() functions to be immensely useful for exploration. You're free to carry out any other exploration of your own.

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv('EICHERMOT.csv')

In [3]:
data.head()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,EICHERMOT,EQ,15-May-2017,29178.35,29403.10,29455.00,28831.00,28915.05,28930.60,29015.64,20026,5.810673e+08,8495,8193,40.91
1,EICHERMOT,EQ,16-May-2017,28930.60,28920.45,29450.00,28820.00,29365.95,29362.50,29107.91,36189,1.053386e+09,11584,16359,45.20
2,EICHERMOT,EQ,17-May-2017,29362.50,29262.00,29300.00,28971.35,28982.05,29093.55,29116.26,18545,5.399610e+08,7918,10611,57.22
3,EICHERMOT,EQ,18-May-2017,29093.55,28900.00,28998.85,28213.00,28213.00,28357.30,28521.49,30153,8.600085e+08,11283,15761,52.27
4,EICHERMOT,EQ,19-May-2017,28357.30,28698.00,28698.00,27756.00,27915.00,27936.05,28024.04,44251,1.240092e+09,21721,20153,45.54

In [4]:
data.tail()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
490,EICHERMOT,EQ,07-May-2019,20349.90,20470.0,20579.90,20270.05,20345.00,20353.20,20366.88,48978,9.975293e+08,12756,19053,38.90
491,EICHERMOT,EQ,08-May-2019,20353.20,20280.0,20470.00,20250.00,20350.00,20336.55,20365.19,43021,8.761307e+08,12698,13056,30.35
492,EICHERMOT,EQ,09-May-2019,20336.55,20315.0,20490.85,20227.60,20390.00,20360.90,20353.58,43718,8.898180e+08,11556,16312,37.31
493,EICHERMOT,EQ,10-May-2019,20360.90,20390.0,20417.55,20301.00,20361.35,20354.00,20346.97,54755,1.114098e+09,11925,25079,45.80
494,EICHERMOT,EQ,13-May-2019,20354.00,20050.0,20121.00,18600.00,18700.00,18751.75,19178.44,342973,6.577686e+09,87269,86209,25.14

In [5]:
data.Date.value_counts()

25-Mar-2019    2
20-Jun-2017    1
19-Feb-2018    1
28-Jun-2018    1
11-Sep-2018    1
08-Aug-2017    1
09-Oct-2018    1
25-Jul-2017    1
07-Mar-2018    1
11-Apr-2019    1
12-Dec-2018    1
09-May-2018    1
24-Dec-2018    1
12-Sep-2017    1
05-Jan-2018    1
29-Mar-2019    1
02-May-2018    1
28-Mar-2018    1
21-Aug-2017    1
27-Feb-2018    1
09-Nov-2017    1
01-Mar-2018    1
12-Dec-2017    1
30-Aug-2018    1
19-Sep-2017    1
01-Feb-2019    1
05-Sep-2018    1
31-Oct-2017    1
14-Nov-2017    1
04-Aug-2017    1
              ..
19-Oct-2018    1
15-Jan-2019    1
15-Feb-2018    1
10-Aug-2017    1
12-Apr-2019    1
23-Jun-2017    1
15-May-2018    1
31-Jul-2017    1
20-Jul-2018    1
11-Jan-2018    1
02-Aug-2018    1
11-Jan-2019    1
15-Jan-2018    1
23-Nov-2017    1
23-Feb-2018    1
23-Oct-2017    1
09-Apr-2018    1
16-Jan-2018    1
06-Aug-2018    1
18-Sep-2018    1
13-Jul-2018    1
09-Nov-2018    1
26-Jun-2018    1
29-Jan-2018    1
01-Aug-2018    1
30-Oct-2018    1
18-Jan-2018    1
16-Feb-2018    1
07-Dec-2018    1
08-Apr-2019    1
Name: Date, Length: 494, dtype: int64

In [6]:
data[data.Date=='25-Mar-2019']

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
462,EICHERMOT,BL,25-Mar-2019,249.95,21446.85,21446.85,21446.85,21446.85,21446.85,21446.85,5004,1.073200e+08,1,5004,100.00
463,EICHERMOT,EQ,25-Mar-2019,21446.85,21390.00,21390.00,21050.95,21191.40,21151.35,21146.55,99423,2.102454e+09,24569,48245,48.52

In [7]:
data.Series.value_counts()

EQ    494
BL      1
Name: Series, dtype: int64

In [8]:
data=data[data.Series=='EQ']
data.reset_index(inplace=True, drop=True)

In [9]:
data.head(5)

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,EICHERMOT,EQ,15-May-2017,29178.35,29403.10,29455.00,28831.00,28915.05,28930.60,29015.64,20026,5.810673e+08,8495,8193,40.91
1,EICHERMOT,EQ,16-May-2017,28930.60,28920.45,29450.00,28820.00,29365.95,29362.50,29107.91,36189,1.053386e+09,11584,16359,45.20
2,EICHERMOT,EQ,17-May-2017,29362.50,29262.00,29300.00,28971.35,28982.05,29093.55,29116.26,18545,5.399610e+08,7918,10611,57.22
3,EICHERMOT,EQ,18-May-2017,29093.55,28900.00,28998.85,28213.00,28213.00,28357.30,28521.49,30153,8.600085e+08,11283,15761,52.27
4,EICHERMOT,EQ,19-May-2017,28357.30,28698.00,28698.00,27756.00,27915.00,27936.05,28024.04,44251,1.240092e+09,21721,20153,45.54

In [10]:
data.tail(5)

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
489,EICHERMOT,EQ,07-May-2019,20349.90,20470.0,20579.90,20270.05,20345.00,20353.20,20366.88,48978,9.975293e+08,12756,19053,38.90
490,EICHERMOT,EQ,08-May-2019,20353.20,20280.0,20470.00,20250.00,20350.00,20336.55,20365.19,43021,8.761307e+08,12698,13056,30.35
491,EICHERMOT,EQ,09-May-2019,20336.55,20315.0,20490.85,20227.60,20390.00,20360.90,20353.58,43718,8.898180e+08,11556,16312,37.31
492,EICHERMOT,EQ,10-May-2019,20360.90,20390.0,20417.55,20301.00,20361.35,20354.00,20346.97,54755,1.114098e+09,11925,25079,45.80
493,EICHERMOT,EQ,13-May-2019,20354.00,20050.0,20121.00,18600.00,18700.00,18751.75,19178.44,342973,6.577686e+09,87269,86209,25.14

In [11]:
data.columns

Index(['Symbol', 'Series', 'Date', 'Prev Close', 'Open Price', 'High Price',
       'Low Price', 'Last Price', 'Close Price', 'Average Price',
       'Total Traded Quantity', 'Turnover', 'No. of Trades', 'Deliverable Qty',
       '% Dly Qt to Traded Qty'],
      dtype='object')

In [12]:
data.shape

(494, 15)

In [13]:
data.describe()

,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
count,494.000000,494.000000,494.000000,494.000000,494.000000,494.000000,494.000000,494.000000,4.940000e+02,494.000000,494.000000,494.000000
mean,26983.775607,27025.830263,27328.877935,26642.895445,26953.491296,26962.669130,26978.380040,67862.196356,1.689181e+09,20987.633603,29421.524291,47.606964
std,3838.978448,3862.087199,3848.221813,3857.188964,3860.120164,3855.515134,3854.897878,62758.208662,1.310023e+09,16248.494693,23001.817102,14.358387
min,18877.250000,18900.000000,19094.900000,18600.000000,18700.000000,18751.750000,18939.760000,3589.000000,1.131677e+08,1231.000000,1191.000000,13.280000
25%,23236.837500,23305.000000,23730.225000,22952.287500,23165.725000,23216.962500,23322.735000,30865.500000,8.955348e+08,11488.250000,14513.750000,37.657500
50%,28166.300000,28235.350000,28508.250000,27884.150000,28160.175000,28159.150000,28168.550000,46515.500000,1.280253e+09,15794.500000,21869.000000,48.425000
75%,29940.425000,29943.937500,30272.100000,29609.500000,29915.700000,29940.425000,29924.602500,83441.250000,2.080619e+09,24599.000000,35967.500000,58.212500
max,32861.950000,33399.950000,33480.000000,32468.100000,32849.000000,32861.950000,32975.240000,481497.000000,1.040866e+10,127954.000000,162372.000000,79.940000

QUERY 2-

1.2 Calculate the maximum, minimum and mean price for the last 90 days. (price=Closing Price unless stated otherwise)

In [14]:
data.iloc[-90:,3:10].describe().astype(int)

,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price
count,90,90,90,90,90,90,90
mean,20767,20779,21042,20468,20705,20719,20740
std,891,880,870,854,876,880,846
min,18877,18900,19094,18600,18700,18751,18939
25%,20217,20247,20476,19993,20271,20204,20255
50%,20530,20560,20774,20300,20502,20518,20499
75%,21147,21246,21455,20844,21109,21129,21123
max,23195,23350,23390,23007,23170,23195,23228

QUERY 3-

1.3 Analyse the data types for each column of the dataframe. Pandas knows how to deal with dates in an intelligent manner. But to make use of Pandas functionality for dates, you need to ensure that the column is of type 'datetime64(ns)'. Change the date column from 'object' type to 'datetime64(ns)' for future convenience. See what happens if you subtract the minimum value of the date column from the maximum value.

In [15]:
data.dtypes

Symbol                     object
Series                     object
Date                       object
Prev Close                float64
Open Price                float64
High Price                float64
Low Price                 float64
Last Price                float64
Close Price               float64
Average Price             float64
Total Traded Quantity       int64
Turnover                  float64
No. of Trades               int64
Deliverable Qty             int64
% Dly Qt to Traded Qty    float64
dtype: object

In [16]:
data['Date_new'] = pd.to_datetime(data['Date'], format='%d-%b-%Y')

In [17]:
data.dtypes

Symbol                            object
Series                            object
Date                              object
Prev Close                       float64
Open Price                       float64
High Price                       float64
Low Price                        float64
Last Price                       float64
Close Price                      float64
Average Price                    float64
Total Traded Quantity              int64
Turnover                         float64
No. of Trades                      int64
Deliverable Qty                    int64
% Dly Qt to Traded Qty           float64
Date_new                  datetime64[ns]
dtype: object

In [18]:
data.head()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty,Date_new
0,EICHERMOT,EQ,15-May-2017,29178.35,29403.10,29455.00,28831.00,28915.05,28930.60,29015.64,20026,5.810673e+08,8495,8193,40.91,2017-05-15
1,EICHERMOT,EQ,16-May-2017,28930.60,28920.45,29450.00,28820.00,29365.95,29362.50,29107.91,36189,1.053386e+09,11584,16359,45.20,2017-05-16
2,EICHERMOT,EQ,17-May-2017,29362.50,29262.00,29300.00,28971.35,28982.05,29093.55,29116.26,18545,5.399610e+08,7918,10611,57.22,2017-05-17
3,EICHERMOT,EQ,18-May-2017,29093.55,28900.00,28998.85,28213.00,28213.00,28357.30,28521.49,30153,8.600085e+08,11283,15761,52.27,2017-05-18
4,EICHERMOT,EQ,19-May-2017,28357.30,28698.00,28698.00,27756.00,27915.00,27936.05,28024.04,44251,1.240092e+09,21721,20153,45.54,2017-05-19

QUERY 4-

1.4 In a separate array , calculate the monthwise VWAP (Volume Weighted Average Price ) of the stock. 
( VWAP = sum(price*volume)/sum(volume) ) 
To know more about VWAP , visit - VWAP definition 
{Hint : Create a new dataframe column ‘Month’. The values for this column can be derived from the ‘Date” column by using appropriate pandas functions. Similarly, create a column ‘Year’ and initialize it. Then use the 'groupby()' function by month and year. Finally, calculate the vwap value for each month (i.e. for each group created).

In [19]:
data.head()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty,Date_new
0,EICHERMOT,EQ,15-May-2017,29178.35,29403.10,29455.00,28831.00,28915.05,28930.60,29015.64,20026,5.810673e+08,8495,8193,40.91,2017-05-15
1,EICHERMOT,EQ,16-May-2017,28930.60,28920.45,29450.00,28820.00,29365.95,29362.50,29107.91,36189,1.053386e+09,11584,16359,45.20,2017-05-16
2,EICHERMOT,EQ,17-May-2017,29362.50,29262.00,29300.00,28971.35,28982.05,29093.55,29116.26,18545,5.399610e+08,7918,10611,57.22,2017-05-17
3,EICHERMOT,EQ,18-May-2017,29093.55,28900.00,28998.85,28213.00,28213.00,28357.30,28521.49,30153,8.600085e+08,11283,15761,52.27,2017-05-18
4,EICHERMOT,EQ,19-May-2017,28357.30,28698.00,28698.00,27756.00,27915.00,27936.05,28024.04,44251,1.240092e+09,21721,20153,45.54,2017-05-19

In [20]:
data['month']=data.Date.str.slice(3)

In [21]:
vwap=np.zeros(data.month.unique().size)
for i,j in enumerate (data.month.unique()):
    temp=data[data.month==j]
    vwap[i]=((temp['Total Traded Quantity']*temp['Average Price']).sum())/((temp['Total Traded Quantity']).sum())

VWAP=pd.DataFrame(vwap,data.month.unique())
VWAP.columns=['VWAP']
VWAP

                  VWAP
May-2017  28114.232251
Jun-2017  28128.339586
Jul-2017  28531.195465
Aug-2017  31062.755945
Sep-2017  31783.750818
Oct-2017  31547.585796
Nov-2017  30715.931559
Dec-2017  29419.214690
Jan-2018  27713.985491
Feb-2018  27552.492338
Mar-2018  28054.987774
Apr-2018  30309.613464
May-2018  30343.433752
Jun-2018  29314.238397
Jul-2018  27821.948923
Aug-2018  28131.782389
Sep-2018  27160.190187
Oct-2018  22272.419028
Nov-2018  23443.709064
Dec-2018  23170.789043
Jan-2019  20389.272869
Feb-2019  20530.878892
Mar-2019  21627.118898
Apr-2019  20640.422955
May-2019  19818.603538

QUERY 5-

1.5Write a function to calculate the average price over the last N days of the stock price data where N is a user defined parameter. Write a second function to calculate the profit/loss percentage over the last N days.
Calculate the average price AND the profit/loss percentages over the course of last -
1 week, 2 weeks, 1 month, 3 months, 6 months and 1 year.
{Note : Profit/Loss percentage between N days is the percentage change between the closing prices of the 2 days }

In [22]:
def meanprice(df,x):
    return df.iloc[-x:,:]['Close Price'].mean()
print(meanprice(data,5))
np.round(meanprice(data,5),2)

20031.28

20031.28

In [23]:
def meanprice(df,x):
    return df.iloc[-x:,:]['Close Price'].mean()
print(meanprice(data,10))
np.round(meanprice(data,10),2)

20212.269999999997

20212.27

In [24]:
def meanprice(df,x):
    return df.iloc[-x:,:]['Close Price'].mean()
print(meanprice(data,21))
np.round(meanprice(data,21),2)

20553.178571428572

20553.18

In [25]:
def meanprice(df,x):
    return df.iloc[-x:,:]['Close Price'].mean()
print(meanprice(data,42))
np.round(meanprice(data,42),2)

20990.43690476191

20990.44

In [26]:
def meanprice(df,x):
    return df.iloc[-x:,:]['Close Price'].mean()
print(meanprice(data,126))
np.round(meanprice(data,126),2)

21482.62499999999

21482.62

In [27]:
def meanprice(df,x):
    return df.iloc[-x:,:]['Close Price'].mean()
print(meanprice(data,252))
np.round(meanprice(data,252),2)

24468.13174603176

24468.13

In [28]:
def profitloss(df,x):
    print (np,round(100*(df.iloc[-1,:]['Close Price']-df.iloc[-(x+1),:]['Close Price'])/df.iloc[-(x+1),:]['Close Price'],2),'%')
    return
profitloss(data,5)

<module 'numpy' from 'F:\\Users\\Nikita\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'> -7.85 %

In [29]:
def profitloss(df,x):
    print (np,round(100*(df.iloc[-1,:]['Close Price']-df.iloc[-(x+1),:]['Close Price'])/df.iloc[-(x+1),:]['Close Price'],2),'%')
    return
profitloss(data,10)

<module 'numpy' from 'F:\\Users\\Nikita\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'> -7.81 %

In [30]:
def profitloss(df,x):
    print (np,round(100*(df.iloc[-1,:]['Close Price']-df.iloc[-(x+1),:]['Close Price'])/df.iloc[-(x+1),:]['Close Price'],2),'%')
    return
profitloss(data,21)

<module 'numpy' from 'F:\\Users\\Nikita\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'> -9.03 %

In [31]:
def profitloss(df,x):
    print (np,round(100*(df.iloc[-1,:]['Close Price']-df.iloc[-(x+1),:]['Close Price'])/df.iloc[-(x+1),:]['Close Price'],2),'%')
    return
profitloss(data,42)

<module 'numpy' from 'F:\\Users\\Nikita\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'> -12.87 %

In [32]:
def profitloss(df,x):
    print (np,round(100*(df.iloc[-1,:]['Close Price']-df.iloc[-(x+1),:]['Close Price'])/df.iloc[-(x+1),:]['Close Price'],2),'%')
    return
profitloss(data,126)

<module 'numpy' from 'F:\\Users\\Nikita\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'> -16.85 %

In [33]:
def profitloss(df,x):
    print (np,round(100*(df.iloc[-1,:]['Close Price']-df.iloc[-(x+1),:]['Close Price'])/df.iloc[-(x+1),:]['Close Price'],2),'%')
    return
profitloss(data,252)

<module 'numpy' from 'F:\\Users\\Nikita\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'> -37.24 %

QUERY 6-

1.6 Add a column 'Day_Perc_Change' where the values are the daily change in percentages i.e. the percentage change between 2 consecutive day's closing prices. Instead of using the basic mathematical formula for computing the same, use 'pct_change()' function provided by Pandas for dataframes. You will note that the first entry of the column will have a ‘Nan’ value. Why does this happen? Either remove the first row, or set the entry to 0 before proceeding.

In [34]:
data['Day_Perc_Change']=100*data['Close Price'].pct_change()
data.iloc[0,-1]=0

In [35]:
data

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty,Date_new,month,Day_Perc_Change
0,EICHERMOT,EQ,15-May-2017,29178.35,29403.10,29455.00,28831.00,28915.05,28930.60,29015.64,20026,5.810673e+08,8495,8193,40.91,2017-05-15,May-2017,0.000000
1,EICHERMOT,EQ,16-May-2017,28930.60,28920.45,29450.00,28820.00,29365.95,29362.50,29107.91,36189,1.053386e+09,11584,16359,45.20,2017-05-16,May-2017,1.492883
2,EICHERMOT,EQ,17-May-2017,29362.50,29262.00,29300.00,28971.35,28982.05,29093.55,29116.26,18545,5.399610e+08,7918,10611,57.22,2017-05-17,May-2017,-0.915964
3,EICHERMOT,EQ,18-May-2017,29093.55,28900.00,28998.85,28213.00,28213.00,28357.30,28521.49,30153,8.600085e+08,11283,15761,52.27,2017-05-18,May-2017,-2.530630
4,EICHERMOT,EQ,19-May-2017,28357.30,28698.00,28698.00,27756.00,27915.00,27936.05,28024.04,44251,1.240092e+09,21721,20153,45.54,2017-05-19,May-2017,-1.485508
5,EICHERMOT,EQ,22-May-2017,27936.05,27936.05,28279.95,27021.50,27111.05,27189.90,27433.60,48952,1.342929e+09,24609,30492,62.29,2017-05-22,May-2017,-2.670922
6,EICHERMOT,EQ,23-May-2017,27189.90,27199.00,27900.00,27120.55,27578.05,27598.25,27621.83,68040,1.879389e+09,28403,32731,48.11,2017-05-23,May-2017,1.501844
7,EICHERMOT,EQ,24-May-2017,27598.25,27600.00,27757.05,27200.00,27400.00,27364.70,27468.84,34680,9.526194e+08,15300,19301,55.65,2017-05-24,May-2017,-0.846249
8,EICHERMOT,EQ,25-May-2017,27364.70,27430.00,28120.00,27321.05,28118.00,28009.45,27714.16,42365,1.174110e+09,17914,22090,52.14,2017-05-25,May-2017,2.356138
9,EICHERMOT,EQ,26-May-2017,28009.45,27915.00,28633.50,27915.00,28270.00,28351.35,28409.72,30251,8.594225e+08,12803,13189,43.60,2017-05-26,May-2017,1.220659
10,EICHERMOT,EQ,29-May-2017,28351.35,28350.70,28495.00,28028.00,28102.00,28172.10,28267.47,21765,6.152415e+08,10443,10246,47.08,2017-05-29,May-2017,-0.632245
11,EICHERMOT,EQ,30-May-2017,28172.10,28235.00,28459.35,27812.05,28207.30,28323.40,28159.02,23730,6.682136e+08,10691,10430,43.95,2017-05-30,May-2017,0.537056
12,EICHERMOT,EQ,31-May-2017,28323.40,28400.00,28549.00,28227.65,28499.85,28435.00,28392.54,42875,1.217330e+09,23609,28511,66.50,2017-05-31,May-2017,0.394020
13,EICHERMOT,EQ,01-Jun-2017,28435.00,28580.00,29019.45,28500.00,28700.00,28793.40,28775.46,47476,1.366144e+09,16722,15384,32.40,2017-06-01,Jun-2017,1.260418
14,EICHERMOT,EQ,02-Jun-2017,28793.40,28970.00,29300.00,28900.00,29151.15,29180.10,29170.43,29954,8.737711e+08,10742,14902,49.75,2017-06-02,Jun-2017,1.343016
15,EICHERMOT,EQ,05-Jun-2017,29180.10,29151.15,29385.00,29151.15,29349.00,29325.50,29302.53,16829,4.931323e+08,7203,10022,59.55,2017-06-05,Jun-2017,0.498285
16,EICHERMOT,EQ,06-Jun-2017,29325.50,29305.00,29388.70,29000.00,29200.00,29191.20,29119.84,16978,4.943966e+08,7958,8480,49.95,2017-06-06,Jun-2017,-0.457963
17,EICHERMOT,EQ,07-Jun-2017,29191.20,29195.90,29775.75,29195.90,29722.50,29713.20,29462.91,46587,1.372589e+09,11870,29825,64.02,2017-06-07,Jun-2017,1.788210
18,EICHERMOT,EQ,08-Jun-2017,29713.20,29714.00,30051.00,29436.00,29738.00,29691.05,29688.10,30851,9.159075e+08,12545,15212,49.31,2017-06-08,Jun-2017,-0.074546
19,EICHERMOT,EQ,09-Jun-2017,29691.05,29740.00,29854.70,29371.05,29571.25,29764.85,29626.08,21623,6.406047e+08,7742,6971,32.24,2017-06-09,Jun-2017,0.248560
20,EICHERMOT,EQ,12-Jun-2017,29764.85,29602.00,29717.70,29272.60,29317.00,29353.45,29488.32,17946,5.291973e+08,8362,9033,50.33,2017-06-12,Jun-2017,-1.382167
21,EICHERMOT,EQ,13-Jun-2017,29353.45,29399.00,29646.60,29000.00,29021.05,29121.25,29317.00,26482,7.763728e+08,13434,13281,50.15,2017-06-13,Jun-2017,-0.791048
22,EICHERMOT,EQ,14-Jun-2017,29121.25,29179.00,29216.90,28921.25,28925.65,29049.50,29029.90,18257,5.299989e+08,8050,10105,55.35,2017-06-14,Jun-2017,-0.246384
23,EICHERMOT,EQ,15-Jun-2017,29049.50,29000.00,29049.50,28505.00,28780.00,28772.00,28757.31,26950,7.750096e+08,11737,12914,47.92,2017-06-15,Jun-2017,-0.955266
24,EICHERMOT,EQ,16-Jun-2017,28772.00,28850.00,28884.85,28578.35,28700.00,28746.90,28749.34,42698,1.227539e+09,10351,32185,75.38,2017-06-16,Jun-2017,-0.087238
25,EICHERMOT,EQ,19-Jun-2017,28746.90,28864.00,28864.00,28400.00,28430.00,28445.20,28584.73,23669,6.765719e+08,7021,15582,65.83,2017-06-19,Jun-2017,-1.049504
26,EICHERMOT,EQ,20-Jun-2017,28445.20,28624.80,28728.00,27860.00,27898.00,27917.40,28043.61,80974,2.270803e+09,13239,63906,78.92,2017-06-20,Jun-2017,-1.855498
27,EICHERMOT,EQ,21-Jun-2017,27917.40,27990.00,27990.00,27300.00,27495.00,27533.20,27526.77,70062,1.928581e+09,14754,39064,55.76,2017-06-21,Jun-2017,-1.376203
28,EICHERMOT,EQ,22-Jun-2017,27533.20,27630.00,27993.90,27511.00,27684.00,27680.85,27786.64,103364,2.872138e+09,13608,76743,74.25,2017-06-22,Jun-2017,0.536262
29,EICHERMOT,EQ,23-Jun-2017,27680.85,27755.00,27817.50,27050.05,27083.00,27166.70,27324.08,27260,7.448545e+08,11606,14728,54.03,2017-06-23,Jun-2017,-1.857421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,EICHERMOT,EQ,27-Mar-2019,21382.00,21401.00,21485.00,20855.65,21024.00,20974.15,21097.93,117588,2.480864e+09,27081,48704,41.42,2019-03-27,Mar-2019,-1.907446
465,EICHERMOT,EQ,28-Mar-2019,20974.15,21024.00,21300.00,20781.05,20924.75,20899.00,20983.19,125561,2.634671e+09,31104,44601,35.52,2019-03-28,Mar-2019,-0.358298
466,EICHERMOT,EQ,29-Mar-2019,20899.00,20795.00,20800.00,20498.00,20516.00,20547.70,20623.74,114105,2.353271e+09,28052,28223,24.73,2019-03-29,Mar-2019,-1.680942
467,EICHERMOT,EQ,01-Apr-2019,20547.70,20788.70,20788.70,19985.50,20015.00,20048.40,20296.18,195397,3.965813e+09,44740,75424,38.60,2019-04-01,Apr-2019,-2.429956
468,EICHERMOT,EQ,02-Apr-2019,20048.40,20310.00,21191.05,20301.00,20610.00,20583.50,20687.17,314645,6.509114e+09,78226,68051,21.63,2019-04-02,Apr-2019,2.669041
469,EICHERMOT,EQ,03-Apr-2019,20583.50,20400.00,20476.00,20112.20,20301.00,20202.70,20255.71,123265,2.496820e+09,32991,28554,23.16,2019-04-03,Apr-2019,-1.850026
470,EICHERMOT,EQ,04-Apr-2019,20202.70,20240.00,20600.00,19921.00,20500.00,20489.55,20173.99,167558,3.380314e+09,41919,47773,28.51,2019-04-04,Apr-2019,1.419860
471,EICHERMOT,EQ,05-Apr-2019,20489.55,20605.00,21029.35,20600.10,20989.00,20980.30,20845.80,127688,2.661758e+09,31100,32344,25.33,2019-04-05,Apr-2019,2.395123
472,EICHERMOT,EQ,08-Apr-2019,20980.30,21124.00,21189.00,20543.60,20585.05,20612.65,20806.73,86524,1.800282e+09,22948,15637,18.07,2019-04-08,Apr-2019,-1.752358
473,EICHERMOT,EQ,09-Apr-2019,20612.65,20699.00,21024.00,20355.00,20900.00,20947.10,20677.35,80256,1.659481e+09,22766,13779,17.17,2019-04-09,Apr-2019,1.622547
474,EICHERMOT,EQ,10-Apr-2019,20947.10,20840.00,21080.00,20650.00,20925.25,20973.75,20911.80,83550,1.747181e+09,21734,13877,16.61,2019-04-10,Apr-2019,0.127225
475,EICHERMOT,EQ,11-Apr-2019,20973.75,20900.00,21073.90,20810.40,20970.00,20998.15,20980.04,97645,2.048596e+09,14229,52037,53.29,2019-04-11,Apr-2019,0.116336
476,EICHERMOT,EQ,12-Apr-2019,20998.15,21027.30,21430.00,20905.05,21280.10,21361.15,21131.52,130351,2.754514e+09,27876,53813,41.28,2019-04-12,Apr-2019,1.728724
477,EICHERMOT,EQ,15-Apr-2019,21361.15,21362.00,21560.00,21251.00,21335.00,21331.95,21445.60,64604,1.385472e+09,15803,12766,19.76,2019-04-15,Apr-2019,-0.136697
478,EICHERMOT,EQ,16-Apr-2019,21331.95,21530.00,21541.80,21200.00,21299.15,21270.55,21325.44,61719,1.316185e+09,17658,20498,33.21,2019-04-16,Apr-2019,-0.287831
479,EICHERMOT,EQ,18-Apr-2019,21270.55,21378.00,21469.95,20949.55,21000.00,21023.90,21148.55,69461,1.468999e+09,16940,14326,20.62,2019-04-18,Apr-2019,-1.159584
480,EICHERMOT,EQ,22-Apr-2019,21023.90,20850.00,20994.80,20345.00,20400.00,20400.85,20568.40,61522,1.265409e+09,18316,15262,24.81,2019-04-22,Apr-2019,-2.963532
481,EICHERMOT,EQ,23-Apr-2019,20400.85,20549.00,20549.00,20204.55,20361.00,20314.90,20316.15,73172,1.486574e+09,21491,24558,33.56,2019-04-23,Apr-2019,-0.421306
482,EICHERMOT,EQ,24-Apr-2019,20314.90,20400.00,20580.00,20140.00,20550.00,20531.55,20364.31,80461,1.638533e+09,24707,30503,37.91,2019-04-24,Apr-2019,1.066459
483,EICHERMOT,EQ,25-Apr-2019,20531.55,20510.45,20639.00,20300.00,20350.00,20340.20,20387.40,91066,1.856599e+09,23308,38302,42.06,2019-04-25,Apr-2019,-0.931980
484,EICHERMOT,EQ,26-Apr-2019,20340.20,20351.00,20452.55,20175.00,20294.00,20330.65,20323.09,63786,1.296329e+09,14655,26051,40.84,2019-04-26,Apr-2019,-0.046951
485,EICHERMOT,EQ,30-Apr-2019,20330.65,20270.00,20400.00,20150.00,20332.00,20368.30,20314.27,65090,1.322256e+09,18114,32131,49.36,2019-04-30,Apr-2019,0.185188
486,EICHERMOT,EQ,02-May-2019,20368.30,19990.00,20630.00,19860.00,20571.00,20565.10,20322.04,109534,2.225954e+09,27515,27418,25.03,2019-05-02,May-2019,0.966207
487,EICHERMOT,EQ,03-May-2019,20565.10,20571.00,20600.00,20340.00,20356.00,20352.35,20434.08,52328,1.069274e+09,12804,19134,36.57,2019-05-03,May-2019,-1.034520
488,EICHERMOT,EQ,06-May-2019,20352.35,20200.00,20485.75,20199.00,20399.25,20349.90,20354.70,55068,1.120893e+09,10712,29815,54.14,2019-05-06,May-2019,-0.012038
489,EICHERMOT,EQ,07-May-2019,20349.90,20470.00,20579.90,20270.05,20345.00,20353.20,20366.88,48978,9.975293e+08,12756,19053,38.90,2019-05-07,May-2019,0.016216
490,EICHERMOT,EQ,08-May-2019,20353.20,20280.00,20470.00,20250.00,20350.00,20336.55,20365.19,43021,8.761307e+08,12698,13056,30.35,2019-05-08,May-2019,-0.081805
491,EICHERMOT,EQ,09-May-2019,20336.55,20315.00,20490.85,20227.60,20390.00,20360.90,20353.58,43718,8.898180e+08,11556,16312,37.31,2019-05-09,May-2019,0.119735
492,EICHERMOT,EQ,10-May-2019,20360.90,20390.00,20417.55,20301.00,20361.35,20354.00,20346.97,54755,1.114098e+09,11925,25079,45.80,2019-05-10,May-2019,-0.033888
493,EICHERMOT,EQ,13-May-2019,20354.00,20050.00,20121.00,18600.00,18700.00,18751.75,19178.44,342973,6.577686e+09,87269,86209,25.14,2019-05-13,May-2019,-7.871917

QUERY 7-

1.7 Add another column 'Trend' whose values are:
'Slight or No change' for 'Day_Perc_Change' in between -0.5 and 0.5
'Slight positive' for 'Day_Perc_Change' in between 0.5 and 1
'Slight negative' for 'Day_Perc_Change' in between -0.5 and -1
'Positive' for 'Day_Perc_Change' in between 1 and 3
'Negative' for 'Day_Perc_Change' in between -1 and -3
'Among top gainers' for 'Day_Perc_Change' in between 3 and 7
'Among top losers' for 'Day_Perc_Change' in between -3 and -7
'Bull run' for 'Day_Perc_Change' >7
'Bear drop' for 'Day_Perc_Change' <-7

In [37]:
data['Trend']=0

for i in np.arange(data.Day_Perc_Change.size):
    if(data.Day_Perc_Change[i]<0.5) and (data.Day_Perc_Change[i]>=-0.5):
        data['Trend'][i]='Slight or No Change'
    elif(data.Day_Perc_Change[i]<1) and (data.Day_Perc_Change[i]>=0.5):
        data['Trend'][i]='Slight Positive'
    elif(data.Day_Perc_Change[i]<-0.5) and (data.Day_Perc_Change[i]>=-1):
        data['Trend'][i]='Slight Negative'
    elif(data.Day_Perc_Change[i]<3) and (data.Day_Perc_Change[i]>=1):
        data['Trend'][i]='Positive'
    elif(data.Day_Perc_Change[i]<-1) and (data.Day_Perc_Change[i]>=-3):
        data['Trend'][i]='Negative'
    elif(data.Day_Perc_Change[i]<7) and (data.Day_Perc_Change[i]>=3):
        data['Trend'][i]='Among top gainers'
    elif(data.Day_Perc_Change[i]<-3) and (data.Day_Perc_Change[i]>=-7):
        data['Trend'][i]='Among top losers'
    elif(data.Day_Perc_Change[i]>=7):
        data['Trend'][i]='Breakout Bull'
    elif(data.Day_Perc_Change[i]<-3):
        data['Trend'][i]='Breakout Bear'

QUERY 8-

1.8 Find the average and median values of the column 'Total Traded Quantity' for each of the types of 'Trend'.
{Hint : use 'groupby()' on the 'Trend' column and then calculate the average and median values of the column 'Total Traded Quantity'}

In [38]:
data.Trend.value_counts()

Slight or No Change    138
Negative               122
Positive                93
Slight Negative         53
Slight Positive         48
Among top gainers       22
Among top losers        13
Breakout Bear            3
Breakout Bull            2
Name: Trend, dtype: int64

In [40]:
trend_vol=data.groupby('Trend')['Total Traded Quantity'].agg(['mean','median'])

In [41]:
trend_vol.astype(int)

                       mean  median
Trend
Among top gainers    129801  128967
Among top losers     182270  150490
Breakout Bear        321435  342973
Breakout Bull        300627  300627
Negative              64012   50169
Positive              69132   47279
Slight Negative       55232   35856
Slight Positive       56096   45222
Slight or No Change   49815   42650

QUERY 9-

1.9 SAVE the dataframe with the additional columns computed as a csv file week2.csv.

In [42]:
data.to_csv('week2.csv',index=False)